import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Under development</h1>


      <span className='tracking-tighter'>This is the future discord bot ! get ready !</span>
      <button className={'btn'}>Discover Our Bot !</button>
    </div>
  )
}

export default Home
